# Generated by Django 5.2.5 on 2025-11-24 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basketapp', '0003_alter_basket_managers_alter_basket_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basket',
            options={'ordering': ('id',), 'verbose_name': 'Корзина', 'verbose_name_plural': 'Корзина'},
        ),
    ]
