# Generated by Django 5.2.5 on 2025-08-27 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_old_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detailed_desc', models.TextField(blank=True, verbose_name='Описание')),
                ('color', models.TextField(blank=True, verbose_name='Цвет')),
                ('dimensions', models.TextField(blank=True, verbose_name='Размеры')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Характеристика товара',
                'verbose_name_plural': 'Характеристики товара',
            },
        ),
    ]
