# Generated by Django 5.2.5 on 2025-08-27 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productfeatures'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfeatures',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Название'),
        ),
    ]
