# Generated by Django 5.2.5 on 2025-08-29 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productfeatures_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimages',
            name='image_type',
            field=models.CharField(blank=True, choices=[('c', 'карточка'), ('s', 'слайдер')], default='s', max_length=1, verbose_name='Тип'),
        ),
    ]
