# Generated by Django 5.2.5 on 2025-09-25 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_productimages_image_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['id'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
    ]
